#!/bin/bash
set -e
if [ -f ~/.XCompose ]; then
	cat <<'EOF' >&2
You already have a `~/.XCompose`.  Move it out of the way.

You may want to merge it into this file, taking care to avoid
duplicates.

Kragen Javier Sitaker <kragen@canonical.org>

EOF
	exit 1
fi
ln -s "$(pwd)/dotXCompose" ~/.XCompose
